### create record
POST http://localhost:3333/api/1/record
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6IiwiaWF0IjoxNjI0MDY3NjQwLCJleHAiOjE2MjQwNjk0NDB9.eklHlJ4FSrSkgHgQ2bdS0eXWFIIiBikst3eVb7oA1yI

{
    "sid":"1",
    "title":"test",
    "episode": "S01E02",
    "timestamp":1621180800000,
    "star": "4.0",
    "status": "0",
    "watched": "0",
    "comment": "sample comment"
}

### get record
GET http://127.0.0.1:3333/api/1/record?pageIndex=1&pageSize=5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6IiwiaWF0IjoxNjI0MDY3NjQwLCJleHAiOjE2MjQwNjk0NDB9.eklHlJ4FSrSkgHgQ2bdS0eXWFIIiBikst3eVb7oA1yI

### 135
POST http://1.117.150.135:3333/api/1/record
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6IiwiaWF0IjoxNjIzOTk0ODQ0LCJleHAiOjE2MjM5OTY2NDR9.SVM43I674M0dwGbcM3uRzGsANEjYKTxbttW63ycgjdY

{
    "sid":"1",
    "name":"test",
    "episode": "S01E02",
    "timestamp":1621180800000,
    "star": "4",
    "status": "0",
    "watched": "0",
    "comment": "sample comment"
}