### get section
GET http://localhost:3030/api/section
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6IiwiaWF0IjoxNjIxNDA4NjQ2LCJleHAiOjE2MjE0MTA0NDZ9.dVHJ_ZIhGKPtzbx-Guaepd4F1mwoMncm9L_8pZoPViU