### 获取用户信息
GET http://localhost:3333/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6IiwiaWF0IjoxNjIxNTI0ODU3LCJleHAiOjE2MjE1MjY2NTd9.YrMjbSOPi7pTajPo9hsiAAAlQCtLZ274TAuCImh5mtc